PatientAppointmentSystem/Models/Day.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientAppointmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Day()
        {
            this.AvailableDays = new HashSet<AvailableDay>();
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int DayId { get; set; }
        public string Day1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailableDay> AvailableDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}

PatientAppointmentSystem/Models/Doctor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientAppointmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
            this.AvailableDays = new HashSet<AvailableDay>();
        }
    
        public int DocId { get; set; }
        public string DoctorName { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> DayId { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailableDay> AvailableDays { get; set; }
        public virtual Day Day { get; set; }
        public virtual Department Department { get; set; }
    }
}

PatientAppointmentSystem/Controllers/AccountsController.cs
using PatientAppointmentSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace PatientAppointmentSystem.Controllers
{
    public class AccountsController : Controller
    {
        DataModelEntities db = new DataModelEntities();
            public ActionResult Login()
        {
            return View();
        } 
        [HttpPost]
        public ActionResult Login(User u)
        {
           bool IsValid = db.Users.Any(x=>x.UserName==u.UserName && x.Password==u.Password);
            if (IsValid)
            {
                Session["UserName"] = u.UserName.ToString();
                FormsAuthentication.SetAuthCookie(u.UserName,false);
                return RedirectToAction("Index","Home");
            }
            else
            {
                ModelState.AddModelError("", "Invalide UserName Or Password");
                return View();
            }
           
        } 
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
           
        }
        public ActionResult signup()
        {
            return View();
        }
        [HttpPost]
        public ActionResult signup(User u)
        {
            var x = db.Users.Add(u);
            db.SaveChanges();

            return RedirectToAction("Login");
        } 
        
       
    }
}

PatientAppointmentSystem/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PatientAppointmentSystem.Models;

namespace PatientAppointmentSystem.Controllers
{
    public class DoctorsController : Controller
    {
        private DataModelEntities db = new DataModelEntities();

        public ActionResult Index()
        {
            var doctors = db.Doctors.Include(d => d.Day).Include(d => d.Department);
            return View(doctors.ToList());
        }

        // GET: Doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: Doctors/Create
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            ViewBag.DayId = new SelectList(db.Days, "DayId", "Day1");
            ViewBag.DeptId = new SelectList(db.Departments, "DeptId", "Name");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DocId,DoctorName,DeptId,DayId,Address,MobileNo")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DayId = new SelectList(db.Days, "DayId", "Day1", doctor.DayId);
            ViewBag.DeptId = new SelectList(db.Departments, "DeptId", "Name", doctor.DeptId);
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            ViewBag.DayId = new SelectList(db.Days, "DayId", "Day1", doctor.DayId);
            ViewBag.DeptId = new SelectList(db.Departments, "DeptId", "Name", doctor.DeptId);
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DocId,DoctorName,DeptId,DayId,Address,MobileNo")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DayId = new SelectList(db.Days, "DayId", "Day1", doctor.DayId);
            ViewBag.DeptId = new SelectList(db.Departments, "DeptId", "Name", doctor.DeptId);
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PatientAppointmentSystem/Controllers/MyAppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PatientAppointmentSystem.Models;

namespace PatientAppointmentSystem.Controllers
{
    public class MyAppointmentController : Controller
    {
        DataModelEntities db = new DataModelEntities();
        public ActionResult Index()
        {
            var appointments = db.Appointments.Include(a => a.AvailableDay).Include(a => a.Department).Include(a => a.Doctor);
            return View(appointments.ToList());
        }
    }
}

PatientAppointmentSystem/Views/Shared/_Day.cshtml
<option value="">-- Select Day --</option>
@if (ViewBag.DayOpt != null)
{
    foreach (var item in ViewBag.DayOpt)
    {
        <option value="@item.Value">@item.Text</option>
    }
}

PatientAppointmentSystem/Views/Shared/_Doctor.cshtml
<option value="">-- Select Doctor --</option>
@if (ViewBag.DocOpt != null)
{
    foreach (var item in ViewBag.DocOpt)
    {
<option value="@item.Value">@item.Text</option>
    }
}

PatientAppointmentSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("SPClinic", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Doctors", "Index", "Doctors", new { area = "" }, new { @class = "navbar-brand" })

                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Admin") || User.IsInRole("Doc"))
                    {
                        @Html.ActionLink("Appointments", "Index", "Appointments", new { area = "" }, new { @class = "navbar-brand" })
                    }
                    else
                    {
                        @Html.ActionLink("My Appointments", "MyAppointment", "Appointments", new { area = "" }, new { @class = "navbar-brand" })

                    }
                }

                @Html.ActionLink("About Us", "AboutUs", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Contact Us", "ContactUs", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class = "navbar-brand">Welcome - @User.Identity.Name</li>
                        <li>
                            @Html.ActionLink("LogOut", "Logout", "Accounts", new { area = "" }, new { @class = "navbar-brand" })
                        </li>

                    }
                    else
                    {
                        <li>
                            @Html.ActionLink("LogIn", "Login", "Accounts", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                        <li>
                            @Html.ActionLink("Resister", "signup", "Accounts", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                    }

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -SPClinic</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>